# Generated by Django 6.0 on 2026-01-04 15:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسنده',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ژانرا')),
            ],
            options={
                'verbose_name': 'ژانرا',
                'verbose_name_plural': 'ژانرا',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان کتاب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='درباره کتاب')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=core.models.imgCoverAddress, verbose_name='کاور کتاب')),
                ('file', models.FileField(upload_to=core.models.bookFileAddress, verbose_name='فایل کتاب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن به سایت')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='مبلغ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='core.author', verbose_name='نویسنده')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.genre', verbose_name='ژنرا')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='امتیاز')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.book', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scores', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امتیاز',
                'verbose_name_plural': 'امتیاز',
                'unique_together': {('book', 'user')},
            },
        ),
    ]
