# Generated by Django 6.0 on 2026-02-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_score_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='اولویت ژانرا')),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.genre', verbose_name='اسم ژانرا')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('position',), name='unique_position')],
            },
        ),
    ]
