# Generated by Django 6.0 on 2026-02-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_navbargenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbargenre',
            name='genre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genre', verbose_name='اسم ژانرا'),
        ),
    ]
