# Generated by Django 6.0 on 2026-02-04 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_navbargenre_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbargenre',
            options={'ordering': ['position'], 'verbose_name': 'ژانرا نوار ناوبری', 'verbose_name_plural': 'ژانرا نوار کاربری'},
        ),
    ]
