# Generated by Django 6.0 on 2026-02-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='pfp_uploads/default_avatar.png', upload_to='pfp_uploads'),
        ),
    ]
