# Generated by Django 6.0 on 2026-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='pfp_uploads/default_avatar.png', upload_to='pfp_uploads', verbose_name='عکس پروفایل'),
        ),
    ]
