# Generated by Django 6.0 on 2026-01-04 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('paid', 'پرداخت شده'), ('refunded', 'بازگشت وجه'), ('canceled', 'لغو شده')], default='pending', max_length=8, verbose_name='وضعیت فاکتور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخته شدن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شدن')),
                ('total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='کل مبلغ فاکتور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='کتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'ایتم های فاکتور',
                'verbose_name_plural': 'ایتم های فاکتور',
                'unique_together': {('order', 'book')},
            },
        ),
    ]
